[window]
opacity = 0.9

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

dimensions = { columns = 130, lines = 32 }

[font]
size = 10.0
normal = { family = "NotoSansMono", style = "Regular" }
